name: Manual Continuous Integration and Environment Setup

on: workflow_dispatch # Manually trigger the workflow

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    set_env_and_lint:
        name: Set Environment and Lint Code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build # will run `yarn build` command

            - name: Run Linter
              uses: borales/actions-yarn@v4
              with:
                  cmd: lint # will run `yarn lint` command

            - name: Run Test
              uses: borales/actions-yarn@v4
              with:
                  cmd: test # will run `yarn test` command
